<xml>
<ToUserName><![CDATA[{{data['to']}}]]></ToUserName>
<FromUserName><![CDATA[{{data['from']}}]]></FromUserName>
<CreateTime>{{int(time())}}</CreateTime>
<MsgType><![CDATA[music]]></MsgType>
<Music>
<Title><![CDATA[{{data['title']}}]]></Title>
<Description><![CDATA[{{data['discription']}}]]></Description>
<MusicUrl><![CDATA[{{data['lqurl']}}]]></MusicUrl>
<HQMusicUrl><![CDATA[{{data['hqurl']}}]]></HQMusicUrl>
</Music>
<FuncFlag>{{data['flag']}}</FuncFlag>
</xml>
